"""
GEE Data Fetcher — V3 (Guna Division Expansion)
================================================
Exports Prithvi-compatible training chips for the ENTIRE Guna Division
using the official MP Forest Department beat boundaries.

Coverage:
  - Guna Division: 8 Ranges, 139 Beats, ~2144 sq km
  - Ranges: Aron, Bamori, Binaganj, Fatehgarh, Maksudangarh,
            North_Guna, Raghogarh, South_Guna

Temporal schema (same as V2):
  T0 = Anchor Date - 365 days  (same-season baseline, last year)
  T1 = Anchor Date - 30 days   (recent context)
  T2 = Anchor Date             (event: bare-soil / felling signature)

Chip strategy (per beat):
  - Positive chips: anchor on S1-radar-pinpointed cut month
  - Negative chips: 75% post-monsoon, 25% summer anchor (phenology)
  - Grid sampling: 224x224 px @ 10m = 2.24km chip, ~6 chips/beat average

Usage:
    # Full Guna Division export to Google Drive
    python src/data/gee_fetch.py --config config.yaml --mode chips

    # Single range only
    python src/data/gee_fetch.py --config config.yaml --mode chips --range Fatehgarh

    # Test mode (direct download, 1 chip per positive)
    python src/data/gee_fetch.py --config config.yaml --test

    # Reference composites only (for dashboard/inference maps)
    python src/data/gee_fetch.py --config config.yaml --mode reference
"""

import src.utils.proj_fix  # noqa: F401  (PROJ/GDAL env fix)

import ee
import io
import os
import json
import yaml
import argparse
import logging
import numpy as np
from pathlib import Path
from datetime import datetime, timedelta
from typing import Optional, List

logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

# ── Band registry ─────────────────────────────────────────────────────────────
_HLS_L30_BANDS  = ["B2",  "B3",  "B4",  "B5",   "B6",  "B7"]   # Landsat 8/9
_HLS_S30_BANDS  = ["B2",  "B3",  "B4",  "B8A",  "B11", "B12"]  # Sentinel-2
_PRITHVI_BANDS  = ["Blue","Green","Red", "NIR",  "SWIR1","SWIR2"]

# Sentinel-1 parameters for cut-date pinpointing
_S1_COLLECTION  = "COPERNICUS/S1_GRD"
_S1_VH_DROP_DB  = 2.0               # dB drop threshold: >2dB = structural canopy loss
_S1_MODE        = "IW"

# Hansen GFC calibration for Guna, Madhya Pradesh (Dry Deciduous Forest)
#
# Canopy threshold set to 5% (not 10%) because Hansen's algorithm was calibrated
# on dense tropical canopy (Amazon/Congo). In MP's open dry-deciduous forest
# (Teak, Sal, Palash at 40-60% cover), even 10% misses the majority of selective
# logging events that FSI ground surveys detect.
#
# The increased noise from 5% is purged by the MANDATORY S1 radar gate:
#   - Radar (C-band VH backscatter) is structurally sensitive — it only drops
#     when woody biomass is physically removed. Leaf-drop does NOT change radar.
#   - Any Hansen polygon that fails the S1 2dB structural test is NOT labelled
#     as a positive — it is DISCARDED entirely (find_s1_cut_month returns None).
#
# Result: a wider spatial net (5%) + harder confirmation gate (mandatory S1)
# produces more true positives with no increase in false positives.
_HANSEN_CANOPY_THR = 5    # treecover2000 minimum % — wide net; S1 is the real filter
_HANSEN_MIN_YEAR   = 15   # lossyear >= 15 (2015) -- start of Sentinel-1 era
_HANSEN_MAX_YEAR   = 24   # lossyear <= 24 (2024)
_HANSEN_MIN_HA     = 0.20 # minimum polygon area in hectares -- below this is sub-pixel noise

# ESRI LULC class IDs
_LULC_TREES     = 2
_LULC_GRASS     = 3
_LULC_FLOODED   = 4
_LULC_SCRUB     = 6
_LULC_RANGELAND = 11
_LULC_CROPS     = 5
_LULC_BARREN    = 7    # bare rock/sand -- hard negative source
_LULC_WATER     = 1    # rivers/waterbodies
_LULC_LAST_YEAR = 2023
_NON_CROP       = [_LULC_TREES, _LULC_GRASS, _LULC_FLOODED, _LULC_SCRUB, _LULC_RANGELAND]
# Hard negative LULC classes: persistently non-forest, visually similar after leaf-drop
_HARD_NEG_LULC  = [_LULC_BARREN, _LULC_WATER]   # rocky outcrops, sandy riverbeds

# Beat shapefile path — read from config.yaml (paths.mp_beats_shp).
# Fallback: local GeoJSON at data/aoi/guna_beats.geojson.
# DO NOT hardcode an absolute Windows path here — it breaks on any other machine.
_MP_BEATS_SHP: Optional[str] = None   # resolved at runtime from config

# Local AOI cache (generated by scripts/export_guna_aoi.py)
_GUNA_BEATS_JSON = "data/aoi/guna_beats.geojson"
_GUNA_DIV_JSON   = "data/aoi/guna_division.geojson"


# ── GEE init ──────────────────────────────────────────────────────────────────

def load_config(path: str) -> dict:
    cfg = yaml.safe_load(open(path))
    # Resolve beat shapefile path from config; store in module-level var so all
    # functions that need it can call get_beats_shp(cfg) instead of hardcoding.
    global _MP_BEATS_SHP
    _MP_BEATS_SHP = cfg.get("paths", {}).get("mp_beats_shp", None)
    return cfg


def get_beats_shp(cfg: dict) -> Optional[str]:
    """Return the beat shapefile path from config, or None if not configured."""
    return cfg.get("paths", {}).get("mp_beats_shp", _MP_BEATS_SHP)


def init_gee(project: Optional[str] = None):
    """Authenticate + initialise GEE. Run `earthengine authenticate` once first."""
    try:
        ee.Initialize(project=project) if project else ee.Initialize()
        log.info("GEE initialised.")
    except Exception as e:
        log.error(f"GEE init failed: {e}")
        log.info("Run `earthengine authenticate` first.")
        raise


# ── AOI loading (local GeoJSON -- no GEE asset needed) ───────────────────────

def load_guna_beats(range_filter: Optional[str] = None):
    """
    Load Guna beat geometries from local GeoJSON or shapefile.
    Returns list of dicts: {range, beat, area_sqkm, geometry (ee.Geometry)}

    Shapefile field names:
      Division, Range, Beat, Beat_Ar (area in sq km), geometry (LCC meters → reprojected to WGS84)
    """
    import geopandas as gpd
    import warnings
    warnings.filterwarnings("ignore")

    # Try local cached GeoJSON first (already in WGS84), then read from shapefile
    if Path(_GUNA_BEATS_JSON).exists():
        gdf = gpd.read_file(_GUNA_BEATS_JSON)
    elif Path(_MP_BEATS_SHP).exists():
        log.info("Local GeoJSON not found -- reading from shapefile (slow)...")
        gdf = gpd.read_file(_MP_BEATS_SHP)
        gdf = gdf[gdf["Division"].str.contains("Guna", case=False, na=False)].copy()
    else:
        raise FileNotFoundError(
            f"Neither {_GUNA_BEATS_JSON} nor {_MP_BEATS_SHP} found. "
            "Run: python scripts/export_guna_aoi.py"
        )

    # Always reproject to WGS84 -- GEE requires lat/lon coordinates
    if gdf.crs is None or gdf.crs.to_epsg() != 4326:
        log.info(f"  Reprojecting from {gdf.crs.name} → WGS84 (EPSG:4326)")
        gdf = gdf.to_crs("EPSG:4326")

    if range_filter:
        all_ranges = sorted(gdf["Range"].unique())
        gdf = gdf[gdf["Range"].str.lower() == range_filter.lower()]
        if len(gdf) == 0:
            raise ValueError(f"No beats found for range '{range_filter}'. "
                             f"Available: {all_ranges}")

    from shapely.geometry import mapping
    beats = []
    for _, row in gdf.iterrows():
        geom_dict = mapping(row.geometry)
        # Beat_Ar is the area field in the MP shapefile (sq km)
        area = float(row.get("Beat_Ar", row.get("Area", row.get("area", 0.0))))
        beats.append({
            "range":    row.get("Range", "unknown"),
            "beat":     row.get("Beat",  "unknown"),
            "area_sqkm": area,
            "geometry": ee.Geometry(geom_dict),
        })

    total_area = sum(b["area_sqkm"] for b in beats)
    log.info(f"Loaded {len(beats)} beats"
             f"{f' (Range: {range_filter})' if range_filter else ' (Guna Division)'}"
             f"  total area ≈ {total_area:.0f} sq km")
    return beats


def load_guna_division_aoi() -> ee.Geometry:
    """Load the full Guna Division boundary as a single dissolved GEE geometry."""
    import geopandas as gpd, warnings
    from shapely.geometry import mapping
    warnings.filterwarnings("ignore")
    if Path(_GUNA_DIV_JSON).exists():
        gdf = gpd.read_file(_GUNA_DIV_JSON)
    else:
        raise FileNotFoundError(f"Run scripts/export_guna_aoi.py first.")
    return ee.Geometry(mapping(gdf.geometry.iloc[0]))


# ── HLS compositing ───────────────────────────────────────────────────────────

def _apply_qa_mask(img: ee.Image) -> ee.Image:
    qa    = img.select("Fmask")
    clear = qa.bitwiseAnd(0b00011110).eq(0)
    return img.updateMask(clear)


def _prep_l30(img): return _apply_qa_mask(img).select(_HLS_L30_BANDS, _PRITHVI_BANDS)
def _prep_s30(img): return _apply_qa_mask(img).select(_HLS_S30_BANDS, _PRITHVI_BANDS)


def hls_window_composite(aoi: ee.Geometry, center_date: str,
                          window_days: int = 45,
                          cloud_thresh: int = 20) -> ee.Image:
    dt  = datetime.strptime(center_date, "%Y-%m-%d")
    t0  = (dt - timedelta(days=window_days)).strftime("%Y-%m-%d")
    t1  = (dt + timedelta(days=window_days)).strftime("%Y-%m-%d")

    l30 = (ee.ImageCollection("NASA/HLS/HLSL30/v002")
           .filterBounds(aoi).filterDate(t0, t1)
           .filter(ee.Filter.lt("CLOUD_COVERAGE", cloud_thresh))
           .map(_prep_l30))
    s30 = (ee.ImageCollection("NASA/HLS/HLSS30/v002")
           .filterBounds(aoi).filterDate(t0, t1)
           .filter(ee.Filter.lt("CLOUD_COVERAGE", cloud_thresh))
           .map(_prep_s30))

    return l30.merge(s30).select(_PRITHVI_BANDS).median().clip(aoi)


def make_three_frame_stack(aoi: ee.Geometry, anchor_date: str,
                            cloud_thresh: int = 20) -> ee.Image:
    """
    18-band image (3 frames x 6 bands):
      Frame 0 (T-365): same-season baseline, previous year
      Frame 1 (T-30):  recent context
      Frame 2 (T+0):   event signature
    """
    anchor = datetime.strptime(anchor_date, "%Y-%m-%d")
    dates  = {
        "0": (anchor - timedelta(days=365)).strftime("%Y-%m-%d"),
        "1": (anchor - timedelta(days=30)).strftime("%Y-%m-%d"),
        "2": anchor_date,
    }
    bands = []
    for frame_idx, center in dates.items():
        comp    = hls_window_composite(aoi, center, window_days=45, cloud_thresh=cloud_thresh)
        renamed = comp.rename([f"{b}_{frame_idx}" for b in _PRITHVI_BANDS])
        bands.append(renamed)
    return ee.Image.cat(bands)   # 18 bands


# ── Sentinel-1 cut-date pinpointing ───────────────────────────────────────────

def find_s1_cut_month(polygon: ee.Geometry, loss_year: int) -> Optional[str]:
    """
    Find the month of structural canopy removal using Sentinel-1 VH backscatter.

    Returns the anchor date string (YYYY-MM-15) if a confirmed VH drop >= 2dB
    is detected, or None if no structural loss is confirmed.

    Returns None (not a fallback date) when:
      - S1 data is missing / sparse for the polygon
      - No month shows a VH drop >= _S1_VH_DROP_DB (2dB)
      - API call fails

    MANDATORY gate: callers MUST discard polygons where this returns None.
    Returning None here is the primary defense against Hansen false positives
    caused by seasonal leaf-drop in dry-deciduous forest. Leaf-drop does NOT
    cause a VH drop -- only physical removal of woody stems does.
    """
    months = ee.List.sequence(1, 12)

    def monthly_vh_mean(m):
        m     = ee.Number(m).int()
        start = ee.Date.fromYMD(loss_year, m, 1)
        end   = start.advance(1, "month")
        s1    = (ee.ImageCollection(_S1_COLLECTION)
                 .filterBounds(polygon).filterDate(start, end)
                 .filter(ee.Filter.eq("instrumentMode", _S1_MODE))
                 .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VH"))
                 .select("VH").mean())
        vh_mean = s1.reduceRegion(
            reducer=ee.Reducer.mean(), geometry=polygon, scale=10, maxPixels=1e6
        ).get("VH")
        return ee.Feature(None, {"month": m, "vh": vh_mean})

    monthly = ee.FeatureCollection(months.map(monthly_vh_mean))
    try:
        data        = monthly.aggregate_array("vh").getInfo()
        months_list = list(range(1, 13))

        # If S1 data is missing for any month, can't confirm structural loss
        if any(v is None for v in data):
            log.debug(f"S1 cut-date: None (missing S1 data for {loss_year})")
            return None

        drops = [(months_list[i+1], data[i] - data[i+1]) for i in range(len(data)-1)]
        valid = [(m, d) for m, d in drops if d >= _S1_VH_DROP_DB]

        if not valid:
            # No month shows a structural VH drop -- likely phenological noise
            log.debug(f"S1 cut-date: None (no VH drop >= {_S1_VH_DROP_DB}dB in {loss_year})")
            return None

        # Anchor to the month with the largest confirmed structural drop
        cut_month = max(valid, key=lambda x: x[1])[0]
        anchor    = f"{loss_year}-{cut_month:02d}-15"
        log.debug(f"S1 cut-date: {anchor} (drop={max(valid, key=lambda x: x[1])[1]:.1f}dB)")
        return anchor

    except Exception as e:
        log.debug(f"S1 cut-date: None (API error: {e})")
        return None


# ── Sentinel-1 monthly VH stack (for CuSum change detection) ─────────────────

def fetch_s1_monthly_vh_stack(
    aoi: "ee.Geometry",
    start_date: str,
    end_date: str,
    scale: int = 20,
    chip_px: int = 224,
) -> "Optional[np.ndarray]":
    """
    Download a monthly Sentinel-1 VH backscatter stack as a numpy array.

    Builds one mean composite per calendar month within [start_date, end_date],
    stacks them into a multi-band GeoTIFF, downloads it via computePixels, and
    returns the array.

    This feeds directly into ``compute_sar_cusum_score()`` in
    ``enhanced_alert_windows.py`` for gradual canopy-loss detection.

    Parameters
    ----------
    aoi        : ee.Geometry — region to download (chip bounding box)
    start_date : "YYYY-MM-DD" — inclusive start (typically anchor_year-01-01)
    end_date   : "YYYY-MM-DD" — inclusive end   (typically anchor_year-12-31)
    scale      : pixel size in metres (20 m default; fast, still sub-canopy)
    chip_px    : output raster size in pixels (224 to match HLS chip)

    Returns
    -------
    np.ndarray of shape (T, H, W) in dB units (float32), or None if:
      - earthengine-api is unavailable
      - > 50% of months have no S1 acquisitions
      - any API / download error occurs

    Notes
    -----
    - Uses IW mode, VH polarisation only (most sensitive to canopy structure)
    - Missing months (cloud-gapped or orbit gaps) are linearly interpolated
      from adjacent months so the CuSum algorithm sees a continuous series
    - Values are in raw linear power (as stored in S1_GRD on GEE), NOT in dB;
      conversion to dB (10*log10) is applied here before returning
    - Scale=20 m gives ~112×112 px at full 2.24 km chip extent; the returned
      array is bilinearly resampled to chip_px × chip_px for consistent shape
    """
    # ee is always available in gee_fetch.py (unconditional import at top).
    # This function will raise naturally if GEE auth is not initialised.

    try:
        start = datetime.strptime(start_date, "%Y-%m-%d")
        end   = datetime.strptime(end_date,   "%Y-%m-%d")
    except ValueError as exc:
        log.error(f"fetch_s1_monthly_vh_stack: bad date format — {exc}")
        return None

    # Build list of (year, month) pairs spanning the date range
    months_to_fetch = []
    cur = start.replace(day=1)
    while cur <= end:
        months_to_fetch.append((cur.year, cur.month))
        # Advance one month
        if cur.month == 12:
            cur = cur.replace(year=cur.year + 1, month=1)
        else:
            cur = cur.replace(month=cur.month + 1)

    T = len(months_to_fetch)
    if T == 0:
        log.warning("fetch_s1_monthly_vh_stack: empty date range.")
        return None

    log.info(f"  S1 VH stack: fetching {T} monthly composites "
             f"({start_date} → {end_date}) at {scale} m")

    # ── Build monthly composites server-side ─────────────────────────────────
    monthly_images = []
    missing_months = []

    for i, (yr, mo) in enumerate(months_to_fetch):
        t_start = ee.Date.fromYMD(yr, mo, 1)
        t_end   = t_start.advance(1, "month")

        s1_month = (
            ee.ImageCollection(_S1_COLLECTION)
            .filterBounds(aoi)
            .filterDate(t_start, t_end)
            .filter(ee.Filter.eq("instrumentMode", _S1_MODE))
            .filter(ee.Filter.listContains("transmitterReceiverPolarisation", "VH"))
            .select("VH")
        )

        # Count scenes; 0 scenes → missing month
        try:
            n_scenes = s1_month.size().getInfo()
        except Exception:
            n_scenes = 0

        if n_scenes == 0:
            missing_months.append(i)
            # Placeholder: constant -9999 image (flagged for interpolation below)
            placeholder = ee.Image.constant(-9999).rename(f"VH_m{i:02d}")
            monthly_images.append(placeholder)
            log.debug(f"    {yr}-{mo:02d}: no S1 scenes (placeholder)")
        else:
            # Mean composite, renamed for band identification
            monthly_images.append(
                s1_month.mean().rename(f"VH_m{i:02d}")
            )
            log.debug(f"    {yr}-{mo:02d}: {n_scenes} scenes")

    # Reject if > 50% of months are missing (stack would be unreliable)
    missing_frac = len(missing_months) / T
    if missing_frac > 0.5:
        log.warning(f"  S1 VH stack: {len(missing_months)}/{T} months missing "
                    f"({missing_frac:.0%}) — skipping CuSum for this chip.")
        return None

    # Stack all bands into one image: (T bands) × (H × W)
    stacked = ee.Image.cat(monthly_images)

    # ── Download via computePixels ────────────────────────────────────────────
    try:
        bounds = aoi.bounds(maxError=1).getInfo()["coordinates"][0]
        xs = [c[0] for c in bounds]
        ys = [c[1] for c in bounds]
        w, e, s, n = min(xs), max(xs), min(ys), max(ys)

        pixel_bytes = ee.data.computePixels({
            "expression": stacked,
            "fileFormat": "GEO_TIFF",
            "grid": {
                "dimensions":      {"width": chip_px, "height": chip_px},
                "affineTransform": {
                    "scaleX": (e - w) / chip_px, "shearX": 0, "translateX": w,
                    "shearY": 0, "scaleY": -(n - s) / chip_px, "translateY": n,
                },
                "crsCode": "EPSG:4326",
            },
        })
    except Exception as exc:
        log.warning(f"  S1 VH stack: computePixels failed — {exc}")
        return None

    # ── Parse GeoTIFF bytes → numpy (T, H, W) ────────────────────────────────
    try:
        import rasterio
        with rasterio.open(io.BytesIO(pixel_bytes)) as src:
            arr = src.read().astype(np.float32)   # (T, H, W) — one band per month
    except Exception as exc:
        log.warning(f"  S1 VH stack: GeoTIFF decode failed — {exc}")
        return None

    # ── Fill missing months by linear interpolation ───────────────────────────
    if missing_months:
        valid_idxs = [i for i in range(T) if i not in missing_months]
        if valid_idxs:
            for mi in missing_months:
                # Find nearest valid neighbours
                before = [v for v in valid_idxs if v < mi]
                after  = [v for v in valid_idxs if v > mi]
                if before and after:
                    b, a     = before[-1], after[0]
                    alpha    = (mi - b) / (a - b)
                    arr[mi]  = arr[b] * (1 - alpha) + arr[a] * alpha
                elif before:
                    arr[mi] = arr[before[-1]]
                elif after:
                    arr[mi] = arr[after[0]]
        log.info(f"  S1 VH stack: interpolated {len(missing_months)} missing months")

    # Replace any remaining -9999 sentinels with NaN
    arr[arr <= -999] = np.nan

    # ── Convert linear power → dB ─────────────────────────────────────────────
    # GEE S1_GRD stores VH in linear power scale (not dB).
    # 10 * log10(power) gives the physical dB value used in all literature.
    with np.errstate(divide="ignore", invalid="ignore"):
        arr_db = np.where(arr > 0, 10.0 * np.log10(arr), np.nan)

    # Replace NaN with column-wise median to avoid CuSum artefacts at edges
    for t in range(T):
        plane = arr_db[t]
        median_val = float(np.nanmedian(plane))
        if np.isnan(median_val):
            median_val = -15.0  # fallback: typical bare-soil VH value
        plane[np.isnan(plane)] = median_val
        arr_db[t] = plane

    log.info(f"  S1 VH stack: shape={arr_db.shape}, "
             f"range=[{arr_db.min():.1f}, {arr_db.max():.1f}] dB, "
             f"{len(missing_months)} months interpolated")

    return arr_db.astype(np.float32)


# ── Label generation ──────────────────────────────────────────────────────────

def get_lulc_change_mask(aoi: ee.Geometry, year: int) -> ee.Image:
    collection = ee.ImageCollection(
        "projects/sat-io/open-datasets/landcover/ESRI_Global-LULC_10m_TS"
    )
    y_curr = min(year, _LULC_LAST_YEAR)
    y_prev = min(year - 1, _LULC_LAST_YEAR)

    def _get(y):
        return (collection.filterDate(f"{y}-01-01", f"{y}-12-31")
                .filterBounds(aoi).mosaic().select("b1").clip(aoi))

    lulc_prev = _get(y_prev)
    lulc_curr = _get(y_curr)

    was_natural = ee.Image(0)
    for cls in _NON_CROP:
        was_natural = was_natural.Or(lulc_prev.eq(cls))

    return was_natural.And(lulc_curr.eq(_LULC_CROPS)).rename("ag_expansion").toByte()


def get_hard_negative_mask(aoi: ee.Geometry, year: int) -> ee.Image:
    """
    Mask of persistently barren/rocky/riverbed pixels -- the #1 false-positive
    source in dry-deciduous forest change detection.

    After leaf-drop, barren rocky outcrops and sandy riverbeds look identical
    to freshly cleared forest in NIR/SWIR composites. Training on chips sampled
    FROM these areas (labeled as no-change negative) forces the model to learn
    the spectral signature difference.

    Strategy:
      - Barren/rocky: ESRI LULC class 7 in BOTH (year-1) AND year
      - Water/sandy riverbed: ESRI LULC class 1 + SRTM slope < 3 degrees
      Both must be persistently bare (not just seasonally so).
    """
    collection = ee.ImageCollection(
        "projects/sat-io/open-datasets/landcover/ESRI_Global-LULC_10m_TS"
    )
    y_curr = min(year, _LULC_LAST_YEAR)
    y_prev = min(year - 1, _LULC_LAST_YEAR)

    def _get(y):
        return (collection.filterDate(f"{y}-01-01", f"{y}-12-31")
                .filterBounds(aoi).mosaic().select("b1").clip(aoi))

    lulc_prev = _get(y_prev)
    lulc_curr = _get(y_curr)

    # Persistently barren (both years)
    barren = lulc_prev.eq(_LULC_BARREN).And(lulc_curr.eq(_LULC_BARREN))

    # Flat water / sandy riverbed (slope < 3 deg keeps out standing water on hills)
    slope   = ee.Terrain.slope(ee.Image("USGS/SRTMGL1_003"))
    riverbed = lulc_curr.eq(_LULC_WATER).And(slope.lt(3))

    return barren.Or(riverbed).rename("hard_negative").toByte()


# ── Hansen forest loss label (alternative / additional label source) ───────────

def get_hansen_loss_mask(aoi: ee.Geometry, year: int) -> ee.Image:
    """
    Binary forest loss mask from Hansen Global Forest Change.

    Calibrated for Guna, Madhya Pradesh (Tropical Dry Deciduous Forest):

      1. treecover2000 >= 15%  (not 10%: Teak/Sal forests are naturally sparse;
                                10% threshold flags open savanna near farm edges)
      2. lossyear == target year, restricted to 2015-2024
                                (pre-2015 has no Sentinel-1 for temporal pinpointing)
      3. S1 radar VH drop >= 2dB (applied per-polygon via find_s1_cut_month)
         Radar ignores leaf-drop -- only responds to structural canopy removal.

    This function returns the spatial mask only (WHERE was lost).
    find_s1_cut_month() determines the anchor date (WHEN it was cut).
    The per-chip minimum area filter (>= 0.20 ha) is applied in the caller.
    """
    hansen    = ee.Image("UMD/hansen/global_forest_change_2024_v1_12")
    loss_year = year - 2000   # e.g. 2022 -> 22
    loss_mask = (
        hansen.select("lossyear").eq(loss_year)
        .And(hansen.select("treecover2000").gte(_HANSEN_CANOPY_THR))  # 15% for dry forest
        .And(hansen.select("lossyear").gte(_HANSEN_MIN_YEAR))         # S1 era only
        .And(hansen.select("lossyear").lte(_HANSEN_MAX_YEAR))
        .clip(aoi)
        .rename("forest_loss")
        .toByte()
    )
    return loss_mask


# ── Dynamic World change label (PRIMARY label source for Guna) ────────────────
#
# Replaces Hansen GFC as the main positive chip source.
# Hansen is blind to Guna's sparse dry-deciduous forest; Dynamic World at 10m
# with probability bands (not hard labels) captures it correctly.
#
# Two-class scheme (matches the alert validation framework in scripts/):
#   Band 1 "deforestation": vegetation → bare ground
#   Band 2 "encroachment":  vegetation → cropland
#
# December composite: trees fully leafed in MP, post-monsoon clear skies,
# avoids phenological false positives from March-June leaf drop.
#
# "Was vegetation" uses BOTH trees_prob AND shrub_prob because DW classifies
# Guna's open 40-60% canopy forest as "shrub_and_scrub" in many scenes.

_DW_THR_TREES  = 0.25   # trees_prob in Dec(year-1) to count as "was forest"
_DW_THR_SHRUB  = 0.35   # shrub_and_scrub_prob (open dry forest often maps here)
_DW_THR_BARE   = 0.50   # bare_prob in Dec(year) to confirm physical removal
_DW_THR_CROPS  = 0.50   # crops_prob in Dec(year) to confirm encroachment
_DW_SIEVE_PX   = 20     # minimum pixels (10m²/px × 20 = 0.20 ha, matching _HANSEN_MIN_HA)

# Set to True to use Dynamic World labels; False to fall back to Hansen
USE_DW_LABELS  = True


def get_dynamic_world_change_mask(aoi: ee.Geometry, year: int) -> ee.Image:
    """
    Two-band change image for year's deforestation and encroachment events.
    Uses December median composites of Dynamic World V1 (Sentinel-2, 10m).

    Bands returned:
        "deforestation"  -- 1 where trees/shrub → bare ground
        "encroachment"   -- 1 where trees/shrub → crops

    The caller must still apply:
        find_s1_cut_month()  -- temporal anchoring (WHEN within the year)
        area filter          -- _HANSEN_MIN_HA (0.20 ha) minimum polygon size

    December is optimal for MP's dry-deciduous phenology:
        - Trees fully leafed (leaf fall Feb–May, regrowth July)
        - Cloud cover < 5% (post-monsoon clear skies)
        - Same seasonal state in both years → no phenological bias
    """
    def dec_composite(y: int) -> ee.Image:
        return (
            ee.ImageCollection("GOOGLE/DYNAMICWORLD/V1")
            .filterDate(f"{y}-12-01", f"{y}-12-31")
            .filterBounds(aoi)
            .select(["trees", "shrub_and_scrub", "crops", "bare"])
            .median()
            .clip(aoi)
        )

    dec_prev = dec_composite(year - 1)
    dec_curr = dec_composite(year)

    # "Was vegetation" = trees OR shrub_and_scrub (captures sparse dry forest)
    was_veg = (
        dec_prev.select("trees").gt(_DW_THR_TREES)
        .Or(dec_prev.select("shrub_and_scrub").gt(_DW_THR_SHRUB))
    )

    # Class 1: physical canopy removal → bare ground
    deforestation = (
        was_veg.And(dec_curr.select("bare").gt(_DW_THR_BARE))
        .rename("deforestation")
        .toByte()
    )

    # Class 2: cleared and cultivated → encroachment
    encroachment = (
        was_veg.And(dec_curr.select("crops").gt(_DW_THR_CROPS))
        .rename("encroachment")
        .toByte()
    )

    # Morphological sieve: erode then dilate to remove isolated pixels < _DW_SIEVE_PX
    # Kernel radius 2 px = 5×5 block → anything smaller disappears
    kernel = ee.Kernel.square(radius=2, units="pixels")
    def sieve(img):
        return img.focal_min(kernel=kernel).focal_max(kernel=kernel)

    return ee.Image.cat([sieve(deforestation), sieve(encroachment)])


def dw_vectors_for_year(aoi: ee.Geometry, year: int,
                         max_polys: int = 200) -> dict:
    """
    Helper: returns vectorised FeatureCollections for both DW change classes.
    Used by export_training_chips() when USE_DW_LABELS=True.

    Returns:
        {
          "deforestation": ee.FeatureCollection,
          "encroachment":  ee.FeatureCollection,
        }
    """
    change     = get_dynamic_world_change_mask(aoi, year)
    min_area   = _HANSEN_MIN_HA * 10_000   # ha → sq m

    def vectorise_band(band_name: str) -> ee.FeatureCollection:
        mask  = change.select(band_name).selfMask()
        vecs  = mask.reduceToVectors(
            geometry=aoi, scale=10,
            geometryType="polygon",
            maxPixels=1e9
        ).limit(max_polys)
        return vecs.map(
            lambda f: f.set("area_m2", f.geometry().area(maxError=1))
                       .set("dw_class", band_name)
        ).filter(ee.Filter.gte("area_m2", min_area))

    return {
        "deforestation": vectorise_band("deforestation"),
        "encroachment":  vectorise_band("encroachment"),
    }


# ── Spatial Friction Map (replaces ConvLSTM risk head) ────────────────────────


def export_spatial_friction_layers(aoi: ee.Geometry, cfg: dict,
                                   output_year: int = 2024):
    """
    Export the 3 GEE layers that feed the Spatial Friction risk score.
    This REPLACES the ConvLSTM prediction head with a physically interpretable
    risk map that Forest Guards can understand and trust.

    Friction layers exported:
      1. dist_to_road:    GRUMP/OSM road network, Euclidean distance (meters)
                          Logging requires transport; risk falls with distance.
      2. edge_of_loss:    Buffer mask around all Hansen loss 2001-output_year;
                          Deforestation acts like a virus -- risk is highest
                          at the boundary of existing cleared land.
      3. slope:           SRTM slope (degrees). Steep ravines (>25 deg) are
                          almost never logged. Flat plateaus are high risk.

    Combined risk score (in Python post-processing):
      risk = w1*(1/dist_to_road) + w2*edge_proximity + w3*(1/slope+1)
    """
    scale   = cfg["gee"]["tile_scale"]
    folder  = "prithvi_guna_friction"

    log.info("Exporting Spatial Friction layers (replacing ConvLSTM risk head)...")

    # 1. Distance to roads (OSM via GEE public dataset)
    roads      = (ee.FeatureCollection("projects/sat-io/open-datasets/OSM/OSM_India_roads")
                  .filterBounds(aoi))
    road_img   = roads.map(lambda f: f.set("val", 1)).reduceToImage(["val"], ee.Reducer.first())
    dist_road  = road_img.unmask(0).Not().cumulativeCost(
        source=road_img.unmask(0), maxDistance=10000
    ).clip(aoi).rename("dist_to_road_m")
    export_to_drive(dist_road, f"friction_dist_road_{output_year}", aoi, scale, folder)

    # 2. Edge-of-loss proximity (Hansen cumulative 2001-output_year)
    hansen       = ee.Image("UMD/hansen/global_forest_change_2024_v1_12")
    cumul_loss   = hansen.select("lossyear").gt(0).And(hansen.select("treecover2000").gte(10))
    edge_buffer  = cumul_loss.fastDistanceTransform().sqrt().multiply(10)  # to meters
    edge_prox    = edge_buffer.clip(aoi).rename("dist_to_loss_edge_m")
    export_to_drive(edge_prox, f"friction_edge_loss_{output_year}", aoi, scale, folder)

    # 3. Terrain slope
    slope = ee.Terrain.slope(ee.Image("USGS/SRTMGL1_003")).clip(aoi).rename("slope_deg")
    export_to_drive(slope, "friction_slope", aoi, scale, folder)

    log.info("  Friction layers submitted. Combine offline:")
    log.info("  risk = w1*(1/dist_road) + w2*(1/dist_edge) + w3*(1/(slope+1))")
    log.info("  Then apply ST_Intersection with beat boundaries for attribution.")


# ── Export helpers ────────────────────────────────────────────────────────────

def export_to_drive(image: ee.Image, description: str,
                    aoi: ee.Geometry, scale: int,
                    folder: str = "prithvi_guna_v3"):
    task = ee.batch.Export.image.toDrive(
        image=image,
        description=description,
        folder=folder,
        fileNamePrefix=description,
        region=aoi,
        scale=scale,
        crs="EPSG:4326",
        maxPixels=1e9,
        fileFormat="GeoTIFF",
    )
    task.start()
    log.info(f"    Export submitted: {description}")
    return task


def export_local(image: ee.Image, out_path: str,
                 aoi: ee.Geometry, scale: int, bands: list):
    """Direct pixel download for small test patches."""
    import numpy as np
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    bounds = aoi.bounds(maxError=1).getInfo()["coordinates"][0]
    xs = [c[0] for c in bounds]; ys = [c[1] for c in bounds]
    w, e, s, n = min(xs), max(xs), min(ys), max(ys)

    pixels = ee.data.computePixels({
        "expression": image.select(bands),
        "fileFormat": "GEO_TIFF",
        "grid": {
            "dimensions":     {"width": 224, "height": 224},
            "affineTransform": {
                "scaleX": (e - w) / 224, "shearX": 0, "translateX": w,
                "shearY": 0, "scaleY": -(n - s) / 224, "translateY": n,
            },
            "crsCode": "EPSG:4326",
        },
    })
    with open(out_path, "wb") as f:
        f.write(pixels)
    log.info(f"    Saved: {out_path} ({len(pixels)//1024} KB)")


# ── Annual reference composites ───────────────────────────────────────────────

def export_annual_composites(aoi: ee.Geometry, cfg: dict, test_mode: bool):
    """Full-AOI annual growing-season composites for dashboard/inference."""
    scale      = cfg["gee"]["tile_scale"]
    cloud_thr  = cfg["gee"]["cloud_threshold"]
    start_year = int(cfg["gee"]["date_range"][0][:4])
    end_year   = int(cfg["gee"]["date_range"][1][:4])
    raw_dir    = cfg["paths"]["raw_dir"]

    log.info("Exporting annual reference composites (Guna Division)...")
    for year in range(start_year, end_year + 1):
        comp = hls_window_composite(aoi, f"{year}-08-15", window_days=60, cloud_thresh=cloud_thr)
        if test_mode:
            export_local(comp, os.path.join(raw_dir, f"hls_{year}_test.tif"),
                         aoi, scale=100, bands=_PRITHVI_BANDS)
        else:
            export_to_drive(comp, f"hls_guna_{year}", aoi, scale)


# ── Main V3 training-chip pipeline (per beat) ─────────────────────────────────

def export_training_chips(beats: list, cfg: dict, test_mode: bool):
    """
    V3 pipeline: exports training chips beat-by-beat across Guna Division.

    For each beat x year:
      1. Get forest-loss positive polygons (Hansen) within the beat boundary
      2. Sample extra positives via LULC change (agri expansion)
      3. For each positive: S1-pinpoint cut month -> anchor date -> 18-band chip
      4. Sample equal negatives from intact forest areas
      5. Export chip image + label to Google Drive (or local in test mode)

    Estimated output: ~800-1200 chips (vs 275 current) covering 2144 sq km
    """
    scale      = cfg["gee"]["tile_scale"]
    cloud_thr  = cfg["gee"]["cloud_threshold"]
    start_year = int(cfg["gee"]["date_range"][0][:4])
    end_year   = int(cfg["gee"]["date_range"][1][:4])
    chip_dir   = cfg["paths"].get("chip_dir", "data/chips")
    folder     = "prithvi_guna_v3"

    Path(chip_dir).mkdir(parents=True, exist_ok=True)

    log.info(f"\nV3 Training chip export: {len(beats)} beats x {end_year-max(start_year,2019)+1} years")
    log.info(f"  Folder: {folder}")
    log.info(f"  Chip dir: {chip_dir}")
    log.info(f"  Test mode: {test_mode}")

    chip_id    = 0
    task_count = 0

    for beat_info in beats:
        beat_aoi  = beat_info["geometry"]
        beat_name = f"{beat_info['range']}_{beat_info['beat']}".replace(" ", "_")
        log.info(f"\n  Beat: {beat_name} (~{beat_info['area_sqkm']:.1f} sq km)")

        for year in range(max(start_year, 2019), end_year + 1):

            # === POSITIVE CHIPS: Hansen forest loss (Triple-Lock) ===
            loss_mask = get_hansen_loss_mask(beat_aoi, year)
            pos_vectors_raw = (loss_mask.selfMask()
                               .reduceToVectors(
                                   geometry=beat_aoi, scale=30,
                                   geometryType="polygon",
                                   maxPixels=1e8)
                               .limit(200))  # cap pre-filter; will reduce after area check

            # 0.20 ha minimum area filter -- sub-pixel Hansen noise elimination.
            # Hansen 30m: 1 pixel = 0.09 ha. Anything <0.20 ha is likely a
            # cloud-shadow artifact or BRDF edge, not a real felling event.
            # A logger clearing even a single row of trees leaves ≥0.20 ha.
            min_area_m2 = _HANSEN_MIN_HA * 10_000  # 0.20 ha = 2000 sq m
            pos_vectors = pos_vectors_raw.map(
                lambda f: f.set("area_m2", f.geometry().area(maxError=1))
            ).filter(ee.Filter.gte("area_m2", min_area_m2)).limit(100)

            try:
                pos_count = pos_vectors.size().getInfo()
            except Exception:
                pos_count = 0

            log.info(f"    {year}: {pos_count} positive polygons (≥{_HANSEN_MIN_HA:.2f} ha)")

            if pos_count > 0:
                features = pos_vectors.toList(pos_vectors.size()).getInfo()

                s1_rejected = 0
                for feat in features:
                    geom      = ee.Geometry(feat["geometry"])
                    centroid  = geom.centroid(maxError=10)
                    chip_geom = centroid.buffer(1120).bounds()

                    # MANDATORY S1 radar gate: reject if no structural VH drop confirmed.
                    # This is the primary defense against Hansen leaf-drop false positives.
                    # At treecover2000 >= 5%, Hansen casts a wide spatial net intentionally;
                    # S1 confirmation is what makes those detections trustworthy.
                    anchor_date = find_s1_cut_month(geom, year)
                    if anchor_date is None:
                        s1_rejected += 1
                        continue  # discard -- phenological noise, not real felling

                    stack = make_three_frame_stack(chip_geom, anchor_date, cloud_thr)
                    label = loss_mask.clip(chip_geom)

                    prefix = f"chip_pos_{beat_name}_{year}_{chip_id:05d}"
                    all_bands = [f"{b}_{i}" for i in range(3) for b in _PRITHVI_BANDS]

                    if test_mode:
                        export_local(stack, f"{chip_dir}/{prefix}_img.tif",
                                     chip_geom, scale=10, bands=all_bands)
                        export_local(label, f"{chip_dir}/{prefix}_lbl.tif",
                                     chip_geom, scale=10, bands=["forest_loss"])
                    else:
                        export_to_drive(stack, f"{prefix}_img", chip_geom, 10, folder)
                        export_to_drive(label, f"{prefix}_lbl", chip_geom, 10, folder)

                    chip_id    += 1
                    task_count += 1

                if s1_rejected:
                    log.info(f"      ↳ S1-rejected (leaf-drop FP): {s1_rejected}/{pos_count}")

            # ============================================================
            # NEGATIVE CHIPS -- 3-tier sampling strategy
            #   50% intact forest, post-monsoon anchor (standard)
            #   25% intact forest, summer anchor   (phenological)
            #   25% rocky/barren/riverbed           (spatial hard negatives)
            # The 3rd tier is critical: after leaf-drop, bare rock looks
            # identical to cleared forest in NIR/SWIR composites.
            # ============================================================
            n_total = max(pos_count * 2, 4)
            n_hard  = max(n_total // 4, 1)   # 25% hard negatives
            n_soft  = n_total - n_hard        # 75% standard / phenological

            intact_mask = loss_mask.eq(0)

            # -- Soft negatives: intact forest --------------------------------
            neg_points = (intact_mask.selfMask()
                          .addBands(ee.Image.pixelLonLat())
                          .sample(region=beat_aoi, scale=120,
                                  numPixels=n_soft, seed=year * 100 + chip_id,
                                  geometries=True))
            try:
                neg_features = neg_points.toList(neg_points.size()).getInfo()
            except Exception:
                neg_features = []

            for i, feat in enumerate(neg_features):
                centroid  = ee.Geometry.Point(feat["geometry"]["coordinates"])
                chip_geom = centroid.buffer(1120).bounds()

                # 1-in-3: summer anchor (phenological hard negative)
                if i % 3 == 0:
                    m           = [4, 5, 6][i % 3]
                    anchor_date = f"{year}-{m:02d}-15"
                    neg_type    = "summer"
                else:
                    anchor_date = f"{year}-09-15"   # post-monsoon full canopy
                    neg_type    = "postmonsoon"

                stack = make_three_frame_stack(chip_geom, anchor_date, cloud_thr)
                label = loss_mask.clip(chip_geom)   # all zeros

                prefix    = f"chip_neg_{neg_type}_{beat_name}_{year}_{chip_id:05d}"
                all_bands = [f"{b}_{i}" for i in range(3) for b in _PRITHVI_BANDS]

                if test_mode:
                    export_local(stack, f"{chip_dir}/{prefix}_img.tif",
                                 chip_geom, scale=10, bands=all_bands)
                else:
                    export_to_drive(stack, f"{prefix}_img", chip_geom, 10, folder)
                    export_to_drive(label, f"{prefix}_lbl", chip_geom, 10, folder)

                chip_id    += 1
                task_count += 1

            # -- Hard negatives: rocky / barren / sandy riverbeds -------------
            hard_neg_mask = get_hard_negative_mask(beat_aoi, year)
            hard_points   = (hard_neg_mask.selfMask()
                             .addBands(ee.Image.pixelLonLat())
                             .sample(region=beat_aoi, scale=120,
                                     numPixels=n_hard, seed=year * 200 + chip_id,
                                     geometries=True))
            try:
                hard_features = hard_points.toList(hard_points.size()).getInfo()
                n_hard_found  = len(hard_features)
            except Exception:
                hard_features = []
                n_hard_found  = 0

            if n_hard_found > 0:
                log.info(f"      {n_hard_found} hard-negative chips (rocky/barren/riverbed)")

            for feat in hard_features:
                centroid  = ee.Geometry.Point(feat["geometry"]["coordinates"])
                chip_geom = centroid.buffer(1120).bounds()
                # Always use Oct anchor: peak dry season, worst-case spectral confusion
                anchor_date = f"{year}-10-15"
                stack = make_three_frame_stack(chip_geom, anchor_date, cloud_thr)
                label = loss_mask.clip(chip_geom)   # all zeros

                prefix    = f"chip_neg_hardrock_{beat_name}_{year}_{chip_id:05d}"
                all_bands = [f"{b}_{i}" for i in range(3) for b in _PRITHVI_BANDS]

                if test_mode:
                    export_local(stack, f"{chip_dir}/{prefix}_img.tif",
                                 chip_geom, scale=10, bands=all_bands)
                else:
                    export_to_drive(stack, f"{prefix}_img", chip_geom, 10, folder)
                    export_to_drive(label, f"{prefix}_lbl", chip_geom, 10, folder)

                chip_id    += 1
                task_count += 1

    log.info(f"\nDone. {task_count} GEE export tasks submitted ({chip_id} chips).")
    if not test_mode:
        log.info("Monitor: https://code.earthengine.google.com/tasks")
        log.info(f"Download chips from Drive folder: {folder}/")
        log.info(f"Then preprocess: python src/data/preprocess.py --chip-dir data/chips")


# ── Entrypoint ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="GEE V3 Data Fetcher -- Guna Division (all 8 ranges, 139 beats)"
    )
    parser.add_argument("--config",  default="config.yaml")
    parser.add_argument("--project", default=None)
    parser.add_argument("--test",    action="store_true",
                        help="Test: direct pixel download (1 beat, 1 year)")
    parser.add_argument("--mode",    default="chips",
                        choices=["reference", "chips", "both"],
                        help="reference=annual composites | chips=training chips | both")
    parser.add_argument("--range",   default=None,
                        help="Only export a specific range (e.g. Fatehgarh, North_Guna)")
    parser.add_argument("--year",    type=int, default=None,
                        help="Only export a specific year (e.g. 2022)")
    args = parser.parse_args()

    cfg = load_config(args.config)
    init_gee(project=args.project or cfg["gee"].get("gee_project"))

    if args.mode in ("chips", "both"):
        beats = load_guna_beats(range_filter=args.range)

        # Optional single-year override (useful for incremental updates)
        if args.year:
            cfg = dict(cfg)
            cfg["gee"] = dict(cfg["gee"])
            cfg["gee"]["date_range"] = [f"{args.year}-01-01", f"{args.year}-12-31"]
            log.info(f"Year override: {args.year} only")

        # Test mode: limit to 1 beat for quick validation
        if args.test and len(beats) > 1:
            log.info("Test mode: limiting to first beat only")
            beats = beats[:1]

        export_training_chips(beats, cfg, args.test)

    if args.mode in ("reference", "both"):
        guna_aoi = load_guna_division_aoi()
        export_annual_composites(guna_aoi, cfg, args.test)
